### ISSUE TITLE
Some kind of timing-related issue

### ISSUE THREAD

**Issue by pragdave** [bitwalker/swarm#70]
I have three nodes that I start independently. 

One acts as a meeting place. The other two do a Node.connect to it when they start, retrying until it becomes available.

Swarm is running on all three, and starts before any nodes are connected.

When I start them manually in three tmux panes, everything is great.

If I start them via a script, it starts up OK, but one or more of them will then error out with a variant of

~~~
17:38:07.758 [error] ** State machine Swarm.Tracker terminating
** Last event = {:cast, {:sync, #PID<15567.213.0>, nil}}
** When server state  = {:syncing, %Swarm.Tracker.TrackerState{clock: nil, nodes: [:"hangman@127.0.0.1"], pending_sync_reqs: [#PID<15567.179.0>, #PID<15565.174.0>], self: :"arcade@127.0.0.1", strategy: #<Ring[:"hangman@127.0.0.1", :"arcade@127.0.0.1"]>, sync_node: :"hangman@127.0.0.1", sync_ref: #Reference<0.1508653593.3076784129.75024>}}
** Reason for termination = :error::function_clause
** Callback mode = :state_functions
** Stacktrace =
**  [{Swarm.IntervalTreeClock, :leq, [nil, nil], [file: 'lib/swarm/tracker/crdt.ex', line: 68]}, {Swarm.IntervalTreeClock, :compare, 2, [file: 'lib/swarm/tracker/crdt.ex', line: 79]}, {Swarm.Tracker, :syncing, 3, [file: 'lib/swarm/tracker/tracker.ex', line: 342]}]
~~~

If I introduce a delay of two seconds between each start, I get this:

~~~

17:44:08.213 [info]  [swarm on words@127.0.0.1] [tracker:init] started

17:44:08.217 [info]  [swarm on words@127.0.0.1] [tracker:cluster_wait] pending sync request from hangman@127.0.0.1
** (Mix) Could not start application dictionary: Dictionary.Application.start(:normal, []) returned an error: shutdown: failed to start child: Dictionary.WordList
    ** (EXIT) exited in: :gen_statem.call(Swarm.Tracker, {:whereis, Dictionary.WordList}, :infinity)
        ** (EXIT) an exception was raised:
            ** (FunctionClauseError) no function clause matching in Swarm.IntervalTreeClock.leq/2
                (swarm) lib/swarm/tracker/crdt.ex:68: Swarm.IntervalTreeClock.leq(nil, nil)
                (swarm) lib/swarm/tracker/crdt.ex:79: Swarm.IntervalTreeClock.compare/2
                (swarm) lib/swarm/tracker/tracker.ex:342: Swarm.Tracker.syncing/3

17:44:08.261 [error] ** State machine Swarm.Tracker terminating
** Last event = {:cast, {:sync, #PID<15618.179.0>, nil}}
** When server state  = {:syncing, %Swarm.Tracker.TrackerState{clock: nil, nodes: [:"hangman@127.0.0.1", :"arcade@127.0.0.1"], pending_sync_reqs: [], self: :"words@127.0.0.1", strategy: #<Ring[:"hangman@127.0.0.1", :"arcade@127.0.0.1", :"words@127.0.0.1"]>, sync_node: :"hangman@127.0.0.1", sync_ref: #Reference<0.441710707.3882090498.99165>}}
** Reason for termination = :error::function_clause
** Callback mode = :state_functions
** Postponed = [{{:call, {#PID<0.190.0>, #Reference<0.441710707.3882090497.101952>}}, {:whereis, Dictionary.WordList}}]
** Stacktrace =
**  [{Swarm.IntervalTreeClock, :leq, [nil, nil], [file: 'lib/swarm/tracker/crdt.ex', line: 68]}, {Swarm.IntervalTreeClock, :compare, 2, [file: 'lib/swarm/tracker/crdt.ex', line: 79]}, {Swarm.Tracker, :syncing, 3, [file: 'lib/swarm/tracker/tracker.ex', line: 342]}]


17:44:08.262 [info]  Application dictionary exited: Dictionary.Application.start(:normal, []) returned an error: shutdown: failed to start child: Dictionary.WordList
    ** (EXIT) exited in: :gen_statem.call(Swarm.Tracker, {:whereis, Dictionary.WordList}, :infinity)
        ** (EXIT) an exception was raised:
            ** (FunctionClauseError) no function clause matching in Swarm.IntervalTreeClock.leq/2
                (swarm) lib/swarm/tracker/crdt.ex:68: Swarm.IntervalTreeClock.leq(nil, nil)
                (swarm) lib/swarm/tracker/crdt.ex:79: Swarm.IntervalTreeClock.compare/2
                (swarm) lib/swarm/tracker/tracker.ex:342: Swarm.Tracker.syncing/3
~~~

Something I'm doing wrong?

Dave

**Comment by bitwalker** [comment]
I know what the problem is, it's something I missed in the change the other day, easy fix. I'll try to push a new release tonight when I'm at my laptop.

**Comment by bitwalker** [comment]
@pragdave I've pushed a commit to master I believe should resolve this issue, and makes some improvements to how the clocks are used and how conflicts are resolved. Please let me know if you are still experiencing this issue, or anything else related to that fix. I'll push a new release once we've had a chance to validate that it behaves correctly.

**Comment by pragdave** [comment]
Will do. I'm off in the weeds for a day, but I'll play with this asap.

**Comment by odarriba** [comment]
I have tested this from master branch and it solves the error for me!

**Comment by bitwalker** [comment]
Great! I'll push a new release today then :)
