### ISSUE TITLE
no function clause matching in :lib.is_op/2

### ISSUE THREAD

**Issue by odarriba** [bitwalker/swarm#71]
Hi!

I'm currently building a distributed application consisting in 6 nodes (by now) with two different applications: 2 nodes with one app and 4 with the other (these last are the ones registering processes individually and in a group).

The thing is that, during deployment (using Kubernetes) we often get `no function clause matching in :lib.is_op/2` exception on the nodes that are not deployed (the ones that detects the topology changes).

For clustering we are using `libcluster` with the Kubernetes strategy, but we have no clue about how this error arises.

Also, we are not using handoff as the registered processes are stateless. Any idea what can be happening?

Here is the stacktrace:

```FunctionClauseError: no function clause matching in :lib.is_op/2
lib/swarm/tracker/crdt.ex:68:in `leq/2'
lib/swarm/tracker/crdt.ex:79:in `compare/2'
lib/swarm/tracker/tracker.ex:342:in `syncing/3'
gen_statem.erl:1240:in `call_state_function/5'
gen_statem.erl:1012:in `loop_event/6'
proc_lib.erl:247:in `init_p_do_apply/3'
```

Thanks in advance for such a great pair of libraries!

**Comment by odarriba** [comment]
Related to this (or I think so) I'm getting this error:

```
    ** (EXIT) exited in: :gen_statem.call(Swarm.Tracker, {:track, "NODE_NAME@NODE_IP", #PID<0.1182.0>, %{}}, :infinity)
        ** (EXIT) an exception was raised:
            ** (FunctionClauseError) no function clause matching in Swarm.IntervalTreeClock.leq/2
                (swarm) lib/swarm/tracker/crdt.ex:68: Swarm.IntervalTreeClock.leq(nil, nil)
                (swarm) lib/swarm/tracker/crdt.ex:79: Swarm.IntervalTreeClock.compare/2
                (swarm) lib/swarm/tracker/tracker.ex:342: Swarm.Tracker.syncing/3
                (stdlib) gen_statem.erl:1240: :gen_statem.call_state_function/5
                (stdlib) gen_statem.erl:1012: :gen_statem.loop_event/6
                (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

To give a bit more of context: this happens when a complete deploy (2 nodes of the cluster) is destroyed and created again (with 4 remaining in the meanwhile).

**Comment by odarriba** [comment]
Checked https://github.com/bitwalker/swarm/issues/70 and seem the same, so closing this!
